using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SerapisPatientAPI.Model.PatientModel
{
    public class PatientBooking
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

        public string BookingID { get; set; }
        public string DoctorBooked { get; set; }
        public string BookingVenue { get; set; }

        [BsonDateTimeOptions]
        public DateTime AppointmentDateTime { get; set; }

        [BsonDateTimeOptions]
        public DateTime DateTimeBooked { get; set; } = DateTime.Now;

        public string SpeciallistType { get; set; }
        public GPS LocationUserBooked { get; set; }


    }

    public partial class GPS
    {
        public string longitude { get; set; }
        public string latitude { get; set; }
    }
}
